name: movie_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  get_it: ^7.6.0
  google_fonts: ^4.0.4
  http: ^0.13.6
  json_annotation: ^4.8.1
  meta: ^1.9.1
  websafe_svg: ^3.0.0+5
  cached_network_image: ^3.2.3
  wiredash: ^1.7.0
  youtube_player_flutter: ^8.1.2
  flutter_inappwebview: ^5.7.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  json_serializable: ^6.6.2

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/images/pngs/
    - assets/images/svgs/
    - assets/languages/
